services:
  addon:
    build: .
    environment:
      - TZ=Europe/Budapest
      - PORT=7000
      - CACHE_TTL_MIN=10
      - SCRAPE_RATE_MS=30000
      - LOG_LEVEL=info
    ports:
      - "7000:7000"
    restart: unless-stopped
